version: '3'
services:
  party1:
    image: rosetta:latest
    network_mode: "host"
    volumes:
      - $PWD/checkpoint:/checkpoint
    command: python3 /Rosetta/example/zkp_resnet/tf-train/main.py --phase train --dataset cifar10 --lr 0.0001 --res_n 101 --epoch 1 --batch_size 128 --train_size 50000 --test_size 10000